spring:
  config:
    activate:
      on-profile: prod
  kafka:
    producer:
      bootstrap-servers: prodhost:9092,prodhost:9093,prodhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
